In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

age = np.random.randint(22, 60, size=20)
experience = age - np.random.randint(20, 25, size=20)  


a = 1500  
b = 1000  
c = 30000  
noise = np.random.normal(0, 5000, size=20)  

salary = a * age + b * experience + c + noise


data = pd.DataFrame({
    'Age': age,
    'Experience': experience,
    'Salary': salary
})


print(data)

    Age  Experience         Salary
0    50          27  128996.806550
1    36          15   97541.531251
2    29           5   75491.466939
3    42          19  121261.390923
4    40          20  109932.513876
5    44          24  114711.445355
6    32          10   92112.724561
7    32          10   81895.781750
8    45          24  122544.317975
9    57          34  139701.649381
10   45          22  112859.069756
11   24           2   68984.306179
12   43          20  118192.332900
13   23           0   65356.841406
14   45          25  121921.758588
15   51          29  133994.481522
16   59          35  146107.390048
17   23           1   61900.778958
18   42          18  108696.806145
19   54          34  150285.611131

In [3]:
import pandas as pd

In [5]:
df=pd.read_csv('Salary_dataset.csv')

In [7]:
df.head()

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [9]:
df.drop(['Unnamed: 0'],axis=1)

    YearsExperience    Salary
0               1.2   39344.0
1               1.4   46206.0
2               1.6   37732.0
3               2.1   43526.0
4               2.3   39892.0
5               3.0   56643.0
6               3.1   60151.0
7               3.3   54446.0
8               3.3   64446.0
9               3.8   57190.0
10              4.0   63219.0
11              4.1   55795.0
12              4.1   56958.0
13              4.2   57082.0
14              4.6   61112.0
15              5.0   67939.0
16              5.2   66030.0
17              5.4   83089.0
18              6.0   81364.0
19              6.1   93941.0
20              6.9   91739.0
21              7.2   98274.0
22              8.0  101303.0
23              8.3  113813.0
24              8.8  109432.0
25              9.1  105583.0
26              9.6  116970.0
27              9.7  112636.0
28             10.4  122392.0
29             10.6  121873.0

In [11]:
from sklearn.model_selection import train_test_split
import numpy as np

In [13]:
from sklearn.linear_model import LinearRegression

In [15]:
reg= LinearRegression()

In [37]:
X=df[['YearsExperience']]
y=df['Salary']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [43]:
X_train

    YearsExperience
27              9.7
11              4.1
17              5.4
22              8.0
5               3.0
16              5.2
8               3.3
14              4.6
23              8.3
20              6.9
1               1.4
29             10.6
6               3.1
4               2.3
18              6.0
19              6.1
9               3.8
7               3.3
25              9.1
3               2.1
0               1.2
21              7.2
15              5.0
12              4.1

In [41]:
reg.fit(X_train,y_train)

LinearRegression()

In [45]:
y_pred=reg.predict(X_test)

In [47]:
from sklearn.metrics import r2_score

In [49]:
r2=r2_score(y_test,y_pred)

In [51]:
r2

0.988169515729126